version: '3.1'

services:
  database:
    image: mariadb
    volumes:
      - database:/var/lib/mysql
      - ./drupal/db/synced_from_production.sql:/docker-entrypoint-initdb.d/synced_from_production.sql
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=drupal

  drupal:
    build: .
    depends_on:
      - database
    ports:
      - 3333:80
    environment:
      - HASH_SALT=hash_salt
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=drupal
      - DATABASE_HOST=database
    volumes:
      - ./files:/var/www/html/sites/default/files
      - ./settings.php:/var/www/html/sites/default/settings.php
      - ./composer.json:/opt/drupal/composer.json
      - ./composer.lock:/opt/drupal/composer.lock
      - ./config:/config-sync
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
    restart: always

volumes:
  database:
